// The last two rungs of the fallback ladder in tarkov-dev.ts: a snapshot of the
// upstream committed to this repo, reachable either over GitHub's CDN or, when
// there is no network at all, from inside the binary.
//
// Format note: the snapshot is stored the way the upstream serves it — one
// language-independent base plus a small dictionary per language — and adapted
// on read. Storing six fully-adapted copies instead would mean six times the
// task payload; sharing the base fits all six languages in 1.38 MB, 0.37 MB
// compressed.
import { adaptTasks, type LocaleDoc } from './adapt';
import { appFetch } from './http';
import type { ApiLang } from './tarkov-dev';
import type { TarkovTask } from './types';

const BASE_URL = 'https://raw.githubusercontent.com/mopocop/Tarkov-moa/main/data/snapshot';
const FETCH_TIMEOUT_MS = 8000;

// `maps` was a second field here until getMaps() was removed as uncalled; the
// snapshot only ever needs to answer for tasks now.
export type SnapshotField = 'tasks';

interface SnapshotBase {
  generatedAt: string | null;
  gameMode?: string;
  tasks: Record<string, unknown>;
  maps: Record<string, unknown>;
  traders: Record<string, unknown>;
}

interface SnapshotLocale {
  tasks: Record<string, string>;
  maps: Record<string, string>;
  traders: Record<string, string>;
}

export interface SnapshotHit<T> {
  data: T;
  generatedAt: number | null;
}

function parseGeneratedAt(value: string | null): number | null {
  if (!value) return null;
  const ms = Date.parse(value);
  return Number.isNaN(ms) ? null : ms;
}

// An empty task list is the placeholder that ships before the workflow's first
// successful run. Treat it as "no snapshot" rather than as "this game has no
// quests" — the difference decides whether the app shows an error or an empty
// screen it cannot explain.
function build<T>(base: SnapshotBase | null, locale: SnapshotLocale | null): SnapshotHit<T> | null {
  if (!base || !locale) return null;
  const asLocale = (d: Record<string, string> | undefined): LocaleDoc => ({ data: d ?? {} });
  let tasks: TarkovTask[];
  try {
    tasks = adaptTasks({
      tasks: { data: { tasks: base.tasks } } as Parameters<typeof adaptTasks>[0]['tasks'],
      tasksLocale: asLocale(locale.tasks),
      maps: { data: { maps: base.maps } } as Parameters<typeof adaptTasks>[0]['maps'],
      mapsLocale: asLocale(locale.maps),
      traders: { data: base.traders } as Parameters<typeof adaptTasks>[0]['traders'],
      tradersLocale: asLocale(locale.traders),
    });
  } catch {
    // A malformed snapshot must not take the app down — it is the last resort,
    // not a source of truth.
    return null;
  }
  if (tasks.length === 0) return null;
  return { data: tasks as T, generatedAt: parseGeneratedAt(base.generatedAt) };
}

async function fetchJson<T>(url: string): Promise<T | null> {
  try {
    const res = await appFetch(url, { signal: AbortSignal.timeout(FETCH_TIMEOUT_MS) });
    if (!res.ok) return null;
    return (await res.json()) as T;
  } catch {
    return null;
  }
}

export async function remoteSnapshot<T>(
  lang: ApiLang,
  field: SnapshotField,
): Promise<SnapshotHit<T> | null> {
  if (field !== 'tasks') return null;
  const [base, locale] = await Promise.all([
    fetchJson<SnapshotBase>(`${BASE_URL}/base.json`),
    fetchJson<SnapshotLocale>(`${BASE_URL}/locale-${lang}.json`),
  ]);
  return build<T>(base, locale);
}

// Loaded with dynamic import rather than a top-level one on purpose: the base is
// ~484 KB and the six locales another ~900 KB, and parsing that at boot to serve
// a tier that almost never runs would cost every launch. Vite splits these into
// their own chunks, so they are only read when the ladder gets here.
const localeModules = import.meta.glob<{ default: SnapshotLocale }>(
  '../../data/snapshot/locale-*.json',
);

export async function bundledSnapshot<T>(
  lang: ApiLang,
  field: SnapshotField,
): Promise<SnapshotHit<T> | null> {
  if (field !== 'tasks') return null;
  try {
    const localeKey = Object.keys(localeModules).find((k) => k.endsWith(`locale-${lang}.json`));
    if (!localeKey) return null;
    const [baseMod, localeMod] = await Promise.all([
      import('../../data/snapshot/base.json'),
      localeModules[localeKey](),
    ]);
    const base = (baseMod as { default: SnapshotBase }).default;
    return build<T>(base, localeMod.default);
  } catch {
    // The files are generated by CI; a build that predates the first successful
    // run simply has no bundled tier.
    return null;
  }
}
